language: elixir
sudo: false
notifications:
  email: false

elixir:
  - 1.5
  - 1.4

otp_release:
  - 20.1
  - 19.3
  - 18.3

script:
  - make testing
after_script:
  - make docs
after_success:
  - bash <(curl -s https://codecov.io/bash)
